DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (id INT PRIMARY KEY, CUSTOMER_NAME VARCHAR(255), GENDER VARCHAR(255), CITY VARCHAR(255));

INSERT INTO CUSTOMER VALUES(1,'Vinayak','Male','Kolkata');
INSERT INTO CUSTOMER VALUES(2,'Dipak','Male','Kolkata');
INSERT INTO CUSTOMER VALUES(3,'Apurba','Male','Kolkata');
